# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit texor.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)


## ----workflow, fig.cap="Workflow of the document conversion conducted by texor."----
knitr::include_graphics("workflow.png")

