---
title: "Response: Converting LaTeX Legacy R Journal Articles into R Markdown Articles using texor and rebib"
output: html_document
---

We thank the editor and reviewers for providing helpful comments on our paper. This is how we have addressed them. *Our response is in italics.*

## General

This article describes how legacy articles of the R Journal between 2009 and 2022 were converted from their original LaTeX format to R Markdown. The process was clearly documented and the results are readily available on the R Journal website today. I'd like to congratulate the authors on completing this seemingly impossible task (at least it was unimaginable to me, given the potential complexity of LaTeX). I wholeheartedly agree with the authors on the benefits of the HTML format, and have also been keeping an eye on the similar effort by arXiv (which was cited at the end of the article). I think the contribution of this article is tremendous, and would like to recommend that we accept it for publication.

*Thank you*

## Detailed comments

Some minor comments:

P6: Is there an extra `x` in `\multicolumnxx{..}`?

*Fixed*

P7: The link on "Pandoc Version > 3.0.0 (if possible latest)" appears to be missing and doesn't work for me.

*Fixed*

P7: The bullet list in Section 3 seems to have a superfluous blank line after the first list item.

*It's not clear how ot fix this. There is nothing special added to the list. It has to be something that latex is doing that we do not control. The html version doesn't have the problem.*

P8: I don't see the link titled "CONTRIBUTE" on the R Journal website as mentioned in Section 5.4.

*This is coming. We expect the current editor will add this, before the paper appears.*

P9: I'd add "(alternate text)" after "alt-text" in case readers are not familiar with the `alt` property of images, or add a link to the text, e.g., https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt.

*Done*

## Code

The packages texor and rebib have clear workflows, and their documentation are well-written.

I didn't fully review the source code since it was rather lengthy, but I could see room for improvement, e.g.,

- The stringr wrappers in texor are not necessary: https://github.com/Abhi-1U/texor/blob/e669ec3f9bf7ad5fb5c4b929f13d18ad7944f735/R/string-tools.R#L3-L28 What we need is `@importFrom stringr str_trim str_detect ...`, and the stringr functions can be used without the `stringr::` qualifier.

- The `stream_editor()` function (https://github.com/Abhi-1U/texor/blob/main/R/stream-editor.R) plays a central role in texor but its implementation didn't take advantage of the built-in vectorization of `gsub()`, i.e., there is absolutely no need to use a `for` loop to modify the input line by line (to mimic `sed`), which is very inefficient, and we can just do `gsub()` on all matches:

    i <- grep(pattern, raw_lines) 
    raw_lines[i] <- gsub(target, replacement, raw_lines[i])

- The supplementary materials (https://github.com/Abhi-1U/texor-rjarticle/tree/master/supplement) are quite helpful, and I really like the examples. It will be nice to also include the intermediate `.Rmd` or `.md` files when converting `.tex` to `.html`, so readers can see how various LaTeX environments are converted to their Markdown counterparts, although the article has already provided some examples in Section 2. The function `texor::latex_to_web()` doesn't seem to have an argument for preserving the intermediate Markdown output, and it may be worth adding one.
