# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ACTOR_PAT: ${{ secrets.GH_ACTOR_T}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r@v2
      
      - name: Pre Install
        run: |
          FILE="DESCRIPTION"
          if [ -f $FILE ]; then
            echo "DESCRIPTION File exists, moving temporarily"
            mkdir desc_temp
            mv $FILE desc_temp
            curl -o DESCRIPTION https://raw.githubusercontent.com/Abhi-1U/texor/master/DESCRIPTION
          else 
            echo "DESCRIPTION File does not exist"
            curl -o DESCRIPTION https://raw.githubusercontent.com/Abhi-1U/texor/master/DESCRIPTION
          fi
        shell: bash
        working-directory: '.'
      - name: install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
              any::plotly
              any::rjtools
              any::DiagrammeR
          needs: check
          cache-version: 2
      - name: Post Install
        run: |
          FILE="DESCRIPTION"
          OGDF="desc_temp/DESCRIPTION"
          if [ -f $OGDF ]; then
            echo "Restoring DESCRIPTION File"
            rm $FILE
            mv $OGDF ./DESCRIPTION
            rm -rf desc_temp
          else
            echo "Deleting DESCRIPTION FILE"
            rm $FILE
          fi
        working-directory: "."
        shell: bash
      - name: Render Rmarkdown files and Commit Results
        run: |
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add *.html *.pdf *.tex
          git commit ${RMD_PATH[*]} -m 'Re-render Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_ACTOR_T }}